# Generated by Django 4.1.7 on 2023-03-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_j_date_member_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='j_date',
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
