# Generated by Django 4.1.7 on 2023-03-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='youtube',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
